name: Check for fixup! commits

on:
  pull_request:
  push:
    branches:
      - release-bot/**

jobs:
  check-for-fixup-commits:
    name: Check for fixup! commits
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for fixup! commits
        shell: bash
        run: |
          if [[ $(git log --pretty=oneline --grep=^fixup! ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}) ]]; then
            echo "fixup! commits found. Squash these before merging."
            exit 1
          fi
